//! Cross-check the reference implementation against the published test vectors
//! in `spec/test-vectors.md` (regenerated by `spec/tools/gen-vectors.py`).
//!
//! This is the anchor proving the impl and the spec agree byte-for-byte:
//! building the §5 session via [`AttestedSession::seal`] must reproduce the
//! vector `session_id`, and building the §6 receipt via [`ReceiptBuilder`] must
//! reproduce the vector's canonical-bytes digest and Ed25519 signature. Any
//! drift in canonicalization or field naming breaks these assertions.

use ed25519_dalek::{Signer, SigningKey};

use private_ai_gateway::aci::canonical;
use private_ai_gateway::aci::identity::keyset_revocation_payload;
use private_ai_gateway::aci::keys::{KeyError, KeyProvider, ALGO_ED25519};
use private_ai_gateway::aci::receipt::{
    canonical_bytes_for_signing, ChannelBinding, ReceiptBuilder, UpstreamVerifiedEvent,
    VerificationResult,
};
use private_ai_gateway::aci::types::{KeyedPublicKey, PublicKeyMaterial, TlsSpki};
use private_ai_gateway::aggregator::session::{
    AttestedSession, Claim, ClaimSource, EvidenceRef, SessionClaims,
};

// §"Fixed keys": receipt key `receipt-1` is Ed25519 from seed 32 × 0x02.
const RECEIPT_KEY_ID: &str = "receipt-1";

// §1 / §2 identity values (identity key = Ed25519 seed 32 × 0x01).
const WORKLOAD_ID: &str = "sha256:57c2c8fa98bcf11441f1eff9ef087db67a5560a026082e96903e15365677b8c0";
const WORKLOAD_KEYSET_DIGEST: &str =
    "sha256:f2fba7e1b1451e0c0231df624f293407692ef939d3e0e55bca723131bea3f1ff";

// §5 attested session id (post-rename: material carries `upstream_name`).
const SESSION_ID: &str = "as_2e9011abafe00fc2902aaa5dedf8373f14e2c4f1a456b854ddb475413547188e";

// §6 receipt signing outputs.
const RECEIPT_CANONICAL_SHA256: &str =
    "sha256:1cd5a27c330ac3a5a82ac30176ba67349b42a64b00868d75ffd23600bf7e7b7c";
const RECEIPT_SIGNATURE: &str = "0861f62296f57a120620e79fc0e91008a187e3793b65be4a0ed355d4617f305e\
     00a19b32463e1feb464f7220bcd37debd892facddc068eebf5ef02202c31910f";

const REQUEST_BODY: &[u8] =
    br#"{"messages":[{"content":"hi","role":"user"}],"model":"demo-model"}"#;
const RESPONSE_BODY: &[u8] = br#"{"choices":[],"id":"chatcmpl-123"}"#;
const ORIGIN: &str = "https://upstream.example.com";

/// A minimal Ed25519 receipt-signing key provider matching the vectors' fixed
/// `receipt-1` key. Only [`Self::receipt_keys`] / [`Self::sign_receipt`] are
/// exercised by [`ReceiptBuilder::finalize`]; the rest are unused here.
struct VectorKeys {
    receipt: SigningKey,
}

impl Default for VectorKeys {
    fn default() -> Self {
        Self {
            receipt: SigningKey::from_bytes(&[0x02; 32]),
        }
    }
}

impl KeyProvider for VectorKeys {
    fn receipt_keys(&self) -> Vec<KeyedPublicKey> {
        vec![KeyedPublicKey {
            key_id: RECEIPT_KEY_ID.to_string(),
            algo: ALGO_ED25519.to_string(),
            public_key_hex: hex::encode(self.receipt.verifying_key().as_bytes()),
        }]
    }

    fn sign_receipt(&self, key_id: &str, canonical_bytes: &[u8]) -> Result<Vec<u8>, KeyError> {
        if key_id != RECEIPT_KEY_ID {
            return Err(KeyError::UnknownReceiptKeyId(key_id.to_string()));
        }
        // Ed25519: raw 64-byte RFC 8032 signature over the canonical bytes.
        Ok(self.receipt.sign(canonical_bytes).to_bytes().to_vec())
    }

    fn identity_public_key(&self) -> PublicKeyMaterial {
        unimplemented!("not exercised by the spec-vector cross-check")
    }
    fn sign_keyset_endorsement(&self, _payload: &[u8]) -> Result<Vec<u8>, KeyError> {
        unimplemented!("not exercised by the spec-vector cross-check")
    }
    fn sign_keyset_revocation(&self, _payload: &[u8]) -> Result<Vec<u8>, KeyError> {
        unimplemented!("not exercised by the spec-vector cross-check")
    }
    fn e2ee_keys(&self) -> Vec<KeyedPublicKey> {
        Vec::new()
    }
    fn decrypt_e2ee(&self, _k: &str, _c: &str, _a: &[u8]) -> Result<Vec<u8>, KeyError> {
        unimplemented!("not exercised by the spec-vector cross-check")
    }
    fn decrypt_legacy_e2ee(
        &self,
        _algo: &str,
        _c: &str,
        _a: Option<&[u8]>,
    ) -> Result<Vec<u8>, KeyError> {
        unimplemented!("not exercised by the spec-vector cross-check")
    }
    fn tls_spkis(&self) -> Vec<TlsSpki> {
        Vec::new()
    }
    fn sign_legacy_message(
        &self,
        _algo: &str,
        _text: &str,
    ) -> Result<private_ai_gateway::aci::keys::LegacySignature, KeyError> {
        unimplemented!("not exercised by the spec-vector cross-check")
    }
    fn is_test_only(&self) -> bool {
        true
    }
}

/// The §5 / §6 claims: `tee_attested` asserted (hardware-proven), all else
/// unknown.
fn vector_claims() -> SessionClaims {
    SessionClaims {
        tee_attested: Claim::asserted(ClaimSource::HardwareProven, "example quote verified"),
        ..SessionClaims::default()
    }
}

fn vector_binding() -> ChannelBinding {
    ChannelBinding::TlsSpkiSha256 {
        origin: ORIGIN.to_string(),
        spki_sha256: "d1".repeat(32),
    }
}

#[test]
fn section5_session_id_matches_vector() {
    // Evidence bytes = ASCII "example-evidence"; the id commits to its digest.
    let evidence_digest = canonical::sha256_hex(b"example-evidence");
    let session = AttestedSession::seal(
        "demo-upstream",
        Some(ORIGIN.to_string()),
        "example/1",
        None,
        vec![vector_binding()],
        vector_claims(),
        EvidenceRef {
            digest: Some(evidence_digest),
            data_uri: None,
        },
        1_750_000_000, // established_at — excluded from the id
        1_750_003_600, // expires_at — excluded from the id
    )
    .unwrap();

    assert_eq!(session.session_id, SESSION_ID);
}

#[test]
fn section6_receipt_canonical_digest_and_signature_match_vector() {
    let keys = VectorKeys::default();
    let mut builder = ReceiptBuilder::new(
        "rcpt-0001".to_string(),
        Some("chatcmpl-123".to_string()),
        Some("demo-model".to_string()),
        WORKLOAD_ID.to_string(),
        WORKLOAD_KEYSET_DIGEST.to_string(),
        "/v1/chat/completions".to_string(),
        "POST".to_string(),
        1_750_000_000,
    );
    builder.add_request_received(REQUEST_BODY).unwrap();
    builder.add_request_forwarded(REQUEST_BODY).unwrap();

    let event = UpstreamVerifiedEvent {
        upstream_name: "demo-upstream".to_string(),
        provider_type: None,
        model_id: "demo-model".to_string(),
        url_origin: Some(ORIGIN.to_string()),
        verifier_id: "example/1".to_string(),
        result: VerificationResult::Verified,
        required: true,
        reason: None,
        evidence: None,
        channel_bindings: vec![vector_binding()],
        provider_claims: None,
    };
    builder
        .add_upstream_verified_with_session(event, SESSION_ID, &vector_claims())
        .unwrap();
    builder
        .add_response_returned(RESPONSE_BODY, RESPONSE_BODY)
        .unwrap();

    let receipt = builder.finalize(&keys, RECEIPT_KEY_ID).unwrap();

    // The user-requested model rides on the receipt (issue #64).
    assert_eq!(receipt.model.as_deref(), Some("demo-model"));

    let canonical_bytes = canonical_bytes_for_signing(&receipt).unwrap();
    assert_eq!(
        canonical::sha256_hex(&canonical_bytes),
        RECEIPT_CANONICAL_SHA256
    );
    assert_eq!(
        receipt.signature.value_hex,
        RECEIPT_SIGNATURE.replace(char::is_whitespace, "")
    );
}

// §4 revocation vector: payload bytes and the Ed25519 identity-key signature.
const REVOCATION_PAYLOAD: &[u8] = br#"{"purpose":"aci.keyset.revocation.v1","workload_keyset_digest":"sha256:f2fba7e1b1451e0c0231df624f293407692ef939d3e0e55bca723131bea3f1ff"}"#;
const REVOCATION_SIGNATURE: &str =
    "5f30e02aa53bb628c7f6410636e9f5e33402d2b0b416a6ed278ea3e6e40b48a9\
     af6ba6e5e55abb89a7ad4627eca444a73cad9d25e22bf239c9c6b362d48ed50f";

#[test]
fn section4_keyset_revocation_payload_and_signature_match_vector() {
    // The revocation payload is built from the revoked keyset digest alone.
    let payload = keyset_revocation_payload(WORKLOAD_KEYSET_DIGEST).unwrap();
    assert_eq!(payload, REVOCATION_PAYLOAD);

    // Signed by the identity key (Ed25519 seed 32 × 0x01) exactly like the
    // endorsement, under a different purpose tag.
    let identity = SigningKey::from_bytes(&[0x01; 32]);
    let signature = identity.sign(&payload);
    assert_eq!(
        hex::encode(signature.to_bytes()),
        REVOCATION_SIGNATURE.replace(char::is_whitespace, "")
    );
}
